name: CI

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: conftest
        uses: ./
        with:
          command: |
            kustomize build test/kustomize | conftest test -p test/policy -
      - name: kubeval
        uses: ./
        with:
          command: |
            kustomize build test/kustomize | kubeval --strict --ignore-missing-schemas
      - name: tools
        uses: ./
        with:
          command: |
            kubectl version --client
            kustomize version
            helm version --client
            helmv3 version
            kubeval --version
            conftest --version
            kubeseal --version
            kubeaudit --help
            yq --version
            jq --version
            go version
